### ISSUE TITLE
Missing information in Vietnamese Hanoi training file

### ISSUE THREAD

**Issue by tresoldi** [sigmorphon/2021-task1#2]
The first entry of the Vietnamese Hanoi training file ( https://github.com/sigmorphon/2021-task1/blob/main/data/medium/vie_hanoi_train.tsv ) has an empty orthographic form (transcription is `n aː n ˧˧`).

As the original word is "nan" (https://en.wiktionary.org/wiki/nan#Vietnamese), it was probably dropped during data cleaning.

**Comment by kylebgorman** [comment]
Thank you for the find there! Yes, that is it. We have one step of prep
that uses Pandas (against my better judgment).

We'll fix that and then close the issue.
